setup:
	mkdir sctl
	mkdir scrb
slow_charge_tl:
	g++ -std=c++23 -O3 slow_charge_tl.cpp -o slow_charge_tl.out
	./slow_charge_tl.out
slow_charge_rb:
	g++ -std=c++23 -O3 slow_charge_rb.cpp -o slow_charge_rb.out
	./slow_charge_rb.out
stalingrado:
	g++ -std=c++23 -O3 stalingrado.cpp -o stalingrado.out
	./stalingrado.out