name: Run benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure CMake
      working-directory: ${{github.workspace}}/benchmark
      run: cmake -B ${{github.workspace}}/benchmark/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/benchmark
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/benchmark/build --config ${{env.BUILD_TYPE}}

    - name: Run benchmarks
      working-directory: ${{github.workspace}}/benchmark
      run: |
        for f in ./*.out
        do
          ./$f
        done
